const database = {
    biblia: [
        {w: "Jardín del Edén", h: "Fruta"},
        {w: "Arca de Noé", h: "Parejas"},
        {w: "Génesis", h: "Principio"},
        {w: "Salomón", h: "Sabiduría"},
        {w: "Daniel", h: "Leones"},
        {w: "Lázaro", h: "Amigo"},
        {w: "Apocalipsis", h: "Revelación"},
        {w: "Maná", h: "Cielo"},
        {w: "Moisés", h: "Canasta"},
        {w: "Isaac", h: "Risa"},
        {w: "Jacob", h: "Sueño"},
        {w: "José", h: "Túnica"},
        {w: "Ezequiel", h: "Huesos"},
        {w: "Juan el Bautista", h: "Miel"},
        {w: "Matusalén", h: "Edad"},
        {w: "Getsemaní", h: "Jardín"},
        {w: "Gólgota", h: "Calavera"},
        {w: "Sodoma", h: "Sal"},
        {w: "Egipto", h: "Pirámides"},
        {w: "Gedeón", h: "Trompetas"},
        {w: "Rut", h: "Espigas"},
        {w: "Noemí", h: "Suegra"},
        {w: "Samuel", h: "Voz"},
        {w: "Elias", h: "Carro"},
        {w: "Eliseo", h: "Aceite"},
        {w: "Job", h: "Paciencia"},
        {w: "Salmos", h: "Canciones"},
        {w: "Proverbios", h: "Consejos"},
        {w: "Lucas", h: "Médico"},
        {w: "Mateo", h: "Impuestos"},
        {w: "Marcos", h: "León"},
        {w: "Juan", h: "Amado"},
        {w: "Zaqueo", h: "Árbol"},
        {w: "Marta", h: "Cocina"},
        {w: "Magdalena", h: "Perfume"},
        {w: "Esteban", h: "Piedras"},
        {w: "Timoteo", h: "Joven"},
        {w: "Bernabé", h: "Consuelo"},
        {w: "Silas", h: "Cárcel"},
        {w: "Betania", h: "Hermanos"},
        {w: "Damasco", h: "Luz"},
        {w: "Éxodo", h: "Salida"},
        {w: "Levítico", h: "Leyes"},
        {w: "Benjamín", h: "Último"},
        {w: "Caín", h: "Hermano"},
        {w: "Abel", h: "Oveja"},
        {w: "Eva", h: "Costilla"},
        {w: "Gabriel", h: "Mensaje"},
        {w: "Miguel", h: "Espada"},
        {w: "Babel", h: "Confusión"},
        {w: "Sinaí", h: "Nube"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Torre de Babel", h: "Idiomas"},
        {w: "Monte Sinaí", h: "Piedra"},
        {w: "Jerusalén", h: "Muro"},
        {w: "Río Jordán", h: "Agua"},
        {w: "Mar Rojo", h: "Camino"},
        {w: "Belén", h: "Estrella"},
        {w: "Nazaret", h: "Pueblo"},
        {w: "Nínive", h: "Perdón"},
        {w: "Jericó", h: "Grito"},
        {w: "Adán", h: "Tierra"},
        {w: "Goliat", h: "Gigante"},
        {w: "Sansón", h: "Pelo"},
        {w: "Jonás", h: "Pez"},
        {w: "María", h: "Madre"},
        {w: "Pedro", h: "Gallo"},
        {w: "Pablo", h: "Cartas"},
        {w: "Abraham", h: "Padre"},
        {w: "Esther", h: "Reina"},
        {w: "Judas Iscariote", h: "Monedas"},
        {w: "El Sembrador", h: "Semilla"},
        {w: "El Buen Samaritano", h: "Viajero"},
        {w: "El Hijo Pródigo", h: "Fiesta"},
        {w: "La Oveja Perdida", h: "Cien"},
        {w: "Los Talentos", h: "Dinero"},
        {w: "El Trigo y la Cizaña", h: "Campo"},
        {w: "La Perla de Gran Precio", h: "Tesoro"},
        {w: "Las Diez Vírgenes", h: "Aceite"},
        {w: "La Casa sobre la Roca", h: "Lluvia"},
        {w: "La Levadura", h: "Pan"},
        {w: "Arca de la Alianza", h: "Cofre"},
        {w: "Honda de David", h: "Puntería"},
        {w: "Manto de Jesús", h: "Ropa"},
        {w: "Zarza Ardiente", h: "Fuego"},
        {w: "Tablas de la Ley", h: "Lista"},
        {w: "Corona de Espinas", h: "Castigo"},
        {w: "Copa de la Última Cena", h: "Vino"},
        {w: "Vara de Aarón", h: "Rama"},
        {w: "Escudo de la Fe", h: "Defensa"},
        {w: "Pan y Peces", h: "Cenas"},
        {w: "El Diluvio", h: "Barco"},
        {w: "La Pascua", h: "Cena"},
        {w: "El Bautismo de Jesús", h: "Paloma"},
        {w: "La Transfiguración", h: "Brillo"},
        {w: "La Resurrección", h: "Vida"},
        {w: "Pentecostés", h: "Viento"},
        {w: "Las Plagas de Egipto", h: "Miedo"},
        {w: "La Crucifixión", h: "Cruz"},
        {w: "La Creación", h: "Mundo"},
        {w: "Las Bodas de Caná", h: "Boda"}
    ],
    comida: [
        {w: "Pizza", h: "Triángulo"},
        {w: "Tenedor", h: "Puntas"},
        {w: "Cuchillo", h: "Filo"},
        {w: "Sartén", h: "Mango"},
        {w: "Licuadora", h: "Aspas"},
        {w: "Microondas", h: "Botón"},
        {w: "Tostadora", h: "Salto"},
        {w: "Rodillo", h: "Masa"},
        {w: "Batidora", h: "Mezcla"},
        {w: "Colador", h: "Agujeros"},
        {w: "Rallador", h: "Queso"},
        {w: "Olla", h: "Tapa"},
        {w: "Delantal", h: "Manchas"},
        {w: "Sacacorchos", h: "Corcho"},
        {w: "Abridor", h: "Lata"},
        {w: "Espátula", h: "Voltear"},
        {w: "Embudos", h: "Cuello"},
        {w: "Mesa", h: "Patas"},
        {w: "Plato", h: "Círculo"},
        {w: "Servilleta", h: "Boca"},
        {w: "Salero", h: "Granos"},
        {w: "Parrilla", h: "Carbón"},
        {w: "Horno", h: "Calor"},
        {w: "Nevera", h: "Puerta"},
        {w: "Congelador", h: "Nieve"},
        {w: "Tabla", h: "Picar"},
        {w: "Molinillo", h: "Pimienta"},
        {w: "Pelador", h: "Piel"},
        {w: "Termo", h: "Temperatura"},
        {w: "Jarra", h: "Pico"},
        {w: "Cucharón", h: "Hondo"},
        {w: "Salchicha", h: "Tripa"},
        {w: "Mermelada", h: "Frasco"},
        {w: "Aceituna", h: "Huesito"},
        {w: "Camarón", h: "Cola"},
        {w: "Langosta", h: "Pinzas"},
        {w: "Ajo", h: "Diente"},
        {w: "Limón", h: "Ácido"},
        {w: "Pimiento", h: "Color"},
        {w: "Zanahoria", h: "Conejo"},
        {w: "Champiñón", h: "Hongo"},
        {w: "Maíz", h: "Granos"},
        {w: "Frijoles", h: "Vaina"},
        {w: "Lentejas", h: "Pequeñas"},
        {w: "Garbanzos", h: "Hummus"},
        {w: "Nuez", h: "Cerebro"},
        {w: "Almendra", h: "Dura"},
        {w: "Pistacho", h: "Verde"},
        {w: "Cereza", h: "Pareja"},
        {w: "Piña", h: "Corona"},
        {w: "Mango", h: "Dulzor"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Hamburguesa", h: "Torre"},
        {w: "Sushi", h: "Palillos"},
        {w: "Taco", h: "Picante"},
        {w: "Espagueti", h: "Enredado"},
        {w: "Helado", h: "Frío"},
        {w: "Chocolate", h: "Dulce"},
        {w: "Palomitas", h: "Cine"},
        {w: "Huevo", h: "Cáscara"},
        {w: "Pollo frito", h: "Balde"},
        {w: "Papas fritas", h: "Sal"},
        {w: "Ensalada", h: "Verde"},
        {w: "Sopa", h: "Cuchara"},
        {w: "Arroz", h: "Blanco"},
        {w: "Pan", h: "Trigo"},
        {w: "Queso", h: "Ratón"},
        {w: "Sandwich", h: "Capas"},
        {w: "Donas", h: "Agujero"},
        {w: "Lasaña", h: "Láminas"},
        {w: "Pescado", h: "Escamas"},
        {w: "Bistec", h: "Vaca"},
        {w: "Hot Dog", h: "Perro"},
        {w: "Galletas", h: "Leche"},
        {w: "Pastel", h: "Vela"},
        {w: "Café", h: "Taza"},
        {w: "Cereal", h: "Desayuno"},
        {w: "Manzana", h: "Gusano"},
        {w: "Plátano", h: "Mono"},
        {w: "Uvas", h: "Racimo"},
        {w: "Tocino", h: "Cerdo"},
        {w: "Burrito", h: "Rollo"},
        {w: "Paella", h: "Sartén"},
        {w: "Nuggets", h: "Caja"},
        {w: "Pancakes", h: "Miel"},
        {w: "Waffles", h: "Cuadros"},
        {w: "Churros", h: "Azúcar"},
        {w: "Gelatina", h: "Movimiento"},
        {w: "Yogur", h: "Bacteria"},
        {w: "Puré", h: "Aplastar"},
        {w: "Nachos", h: "Triángulos"},
        {w: "Alitas", h: "Hueso"},
        {w: "Brocheta", h: "Palito"},
        {w: "Empanada", h: "Relleno"},
        {w: "Ravioles", h: "Pasta"},
        {w: "Pavo", h: "Navidad"},
        {w: "Sandía", h: "Pepitas"},
        {w: "Chicle", h: "Bomba"},
        {w: "Paleta", h: "Lengua"},
        {w: "Mantequilla", h: "Untar"},
        {w: "Cebolla", h: "Lágrima"}
    ],
    profesiones: [
        {w: "Bombero", h: "Agua"},
        {w: "Ingeniero", h: "Casco"},
        {w: "Esteticista", h: "Piel"},
        {w: "Diseñador", h: "Logo"},
        {w: "Psicólogo", h: "Diván"},
        {w: "Programador", h: "Código"},
        {w: "Maquillador", h: "Sombras"},
        {w: "Locutor", h: "Micrófono"},
        {w: "Enfermera", h: "Inyección"},
        {w: "Azafata", h: "Pasillo"},
        {w: "Barista", h: "Grano"},
        {w: "Sommelier", h: "Copa"},
        {w: "Artesano", h: "Barro"},
        {w: "Joyero", h: "Pinzas"},
        {w: "Relojero", h: "Engranaje"},
        {w: "Topógrafo", h: "Trípode"},
        {w: "Biólogo", h: "Microscopio"},
        {w: "Geólogo", h: "Roca"},
        {w: "Meteorólogo", h: "Mapa"},
        {w: "Entrenador", h: "Cronómetro"},
        {w: "Árbitro", h: "Tarjeta"},
        {w: "Coreógrafo", h: "Paso"},
        {w: "Modista", h: "Maniquí"},
        {w: "Tapicero", h: "Grapas"},
        {w: "Soldador", h: "Chispa"},
        {w: "Cerrajero", h: "Llave"},
        {w: "Vidriero", h: "Ventana"},
        {w: "Editor", h: "Corte"},
        {w: "Contador", h: "Calculadora"},
        {w: "Economista", h: "Gráfica"},
        {w: "Diputado", h: "Voto"},
        {w: "Juez", h: "Mazo"},
        {w: "Notario", h: "Sello"},
        {w: "Aduanero", h: "Maleta"},
        {w: "Fumigador", h: "Veneno"},
        {w: "Exterminador", h: "Rata"},
        {w: "Socorrista", h: "Flotador"},
        {w: "Escolta", h: "Auricular"},
        {w: "Afilador", h: "Piedra"},
        {w: "Deshollinador", h: "Hollín"},
        {w: "Cabrero", h: "Bastón"},
        {w: "Pastor", h: "Rebaño"},
        {w: "Apicultor", h: "Panal"},
        {w: "Leñador", h: "Hacha"},
        {w: "Minero", h: "Pico"},
        {w: "Peleador", h: "Guantes"},
        {w: "Torero", h: "Capote"},
        {w: "Astrónomo", h: "Telescopio"},
        {w: "Óptico", h: "Gafas"},
        {w: "Farmacéutico", h: "Receta"},
        {w: "Traductor", h: "Diccionario"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Médico", h: "Salud"},
        {w: "Policía", h: "Orden"},
        {w: "Profesor", h: "Tablero"},
        {w: "Cocinero", h: "Sartén"},
        {w: "Astronauta", h: "Estrellas"},
        {w: "Peluquero", h: "Tijeras"},
        {w: "Mecánico", h: "Tuerca"},
        {w: "Carpintero", h: "Madera"},
        {w: "Pintor", h: "Brocha"},
        {w: "Fotógrafo", h: "Lente"},
        {w: "Cantante", h: "Voz"},
        {w: "Cartero", h: "Sobre"},
        {w: "Veterinario", h: "Mascotas"},
        {w: "Dentista", h: "Muela"},
        {w: "Arquitecto", h: "Plano"},
        {w: "Granjero", h: "Tractor"},
        {w: "Científico", h: "Tubo"},
        {w: "Piloto", h: "Nube"},
        {w: "Jardinero", h: "Pala"},
        {w: "Abogado", h: "Leyes"},
        {w: "Periodista", h: "Noticia"},
        {w: "Mesero", h: "Bandeja"},
        {w: "Panadero", h: "Harina"},
        {w: "Costurera", h: "Aguja"},
        {w: "Salvavidas", h: "Silbato"},
        {w: "Electricista", h: "Cable"},
        {w: "Plomero", h: "Tubo"},
        {w: "Barrendero", h: "Escoba"},
        {w: "Cajero", h: "Dinero"},
        {w: "Actor", h: "Guion"},
        {w: "Bailarina", h: "Puntas"},
        {w: "Bibliotecario", h: "Silencio"},
        {w: "Zapatero", h: "Suela"},
        {w: "Albañil", h: "Ladrillo"},
        {w: "Arqueólogo", h: "Huesos"},
        {w: "Detective", h: "Lupa"},
        {w: "Escultor", h: "Cincel"},
        {w: "Payaso", h: "Nariz"},
        {w: "Joyero", h: "Anillo"},
        {w: "Pescador", h: "Red"},
        {w: "Escritor", h: "Pluma"},
        {w: "Deportista", h: "Medalla"},
        {w: "Buzo", h: "Oxígeno"},
        {w: "Mago", h: "Varita"},
        {w: "Soldado", h: "Casco"},
        {w: "Chofer", h: "Volante"},
        {w: "Sastre", h: "Medida"},
        {w: "Cuerpo de baile", h: "Escenario"},
        {w: "Guardia", h: "Garita"}
    ],
    objetos: [
        {w: "Sombrilla", h: "Lluvia"},
        {w: "Marimba", h: "Teclado"},
        {w: "Caracol", h: "Sopa"},
        {w: "Comal", h: "Tortilla"},
        {w: "Machete", h: "Campo"},
        {w: "Hamaca", h: "Nudos"},
        {w: "Poncho", h: "Frío"},
        {w: "Sombrero de Junco", h: "Santa Bárbara"},
        {w: "Cayuco", h: "Remo"},
        {w: "Guacal", h: "Cuchara"},
        {w: "Petate", h: "Suelo"},
        {w: "Jarrón de Barro", h: "Lenca"},
        {w: "Tunante", h: "Baile"},
        {w: "Pito de Barro", h: "Silbido"},
        {w: "Ancla", h: "Barco"},
        {w: "Brújula", h: "Norte"},
        {w: "Escalera", h: "Peldaño"},
        {w: "Extintor", h: "Fuego"},
        {w: "Binoculares", h: "Lejos"},
        {w: "Mapa", h: "País"},
        {w: "Estufa", h: "Llama"},
        {w: "Taladro", h: "Agujero"},
        {w: "Grapa", h: "Papeles"},
        {w: "Cinta Métrica", h: "Centímetro"},
        {w: "Destornillador", h: "Tornillo"},
        {w: "Alicate", h: "Presión"},
        {w: "Serrucho", h: "Dientes"},
        {w: "Embudo", h: "Líquido"},
        {w: "Periódico", h: "Noticia"},
        {w: "Sobre", h: "Carta"},
        {w: "Sello", h: "Tinta"},
        {w: "Gis", h: "Pizarra"},
        {w: "Borrador", h: "Error"},
        {w: "Pincel", h: "Acuarela"},
        {w: "Caballete", h: "Cuadro"},
        {w: "Guitarra", h: "Cuerdas"},
        {w: "Tambor", h: "Cuero"},
        {w: "Flauta", h: "Viento"},
        {w: "Megáfono", h: "Grito"},
        {w: "Micrófono", h: "Escenario"},
        {w: "Audífonos", h: "Oreja"},
        {w: "Teclado", h: "Letras"},
        {w: "Mouse", h: "Flecha"},
        {w: "Monitor", h: "Pantalla"},
        {w: "Impresora", h: "Tinta"},
        {w: "Escáner", h: "Copia"},
        {w: "Enchufe", h: "Pared"},
        {w: "Bombillo", h: "Rosca"},
        {w: "Fusible", h: "Corte"},
        {w: "Imán", h: "Atracción"},
        {w: "Termómetro", h: "Fiebre"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Reloj", h: "Tiempo"},
        {w: "Espejo", h: "Reflejo"},
        {w: "Llave", h: "Cerradura"},
        {w: "Cámara", h: "Foto"},
        {w: "Lentes", h: "Ojos"},
        {w: "Martillo", h: "Clavo"},
        {w: "Cepillo", h: "Dientes"},
        {w: "Almohada", h: "Sueño"},
        {w: "Libro", h: "Hojas"},
        {w: "Tijeras", h: "Corte"},
        {w: "Lámpara", h: "Luz"},
        {w: "Celular", h: "Llamada"},
        {w: "Bicicleta", h: "Pedal"},
        {w: "Maleta", h: "Viaje"},
        {w: "Escoba", h: "Piso"},
        {w: "Plancha", h: "Ropa"},
        {w: "Control", h: "Botón"},
        {w: "Vaso", h: "Vidrio"},
        {w: "Silla", h: "Patas"},
        {w: "Cuchara", h: "Boca"},
        {w: "Toalla", h: "Secar"},
        {w: "Peine", h: "Cabello"},
        {w: "Botella", h: "Tapa"},
        {w: "Cartera", h: "Billetes"},
        {w: "Cinturón", h: "Cintura"},
        {w: "Jabón", h: "Burbuja"},
        {w: "Zapatos", h: "Pies"},
        {w: "Globo", h: "Aire"},
        {w: "Paraguas", h: "Nube"},
        {w: "Lápiz", h: "Goma"},
        {w: "Calculadora", h: "Números"},
        {w: "Bolsa", h: "Plástico"},
        {w: "Ventilador", h: "Viento"},
        {w: "Radio", h: "Sonido"},
        {w: "Candado", h: "Hierro"},
        {w: "Anillo", h: "Dedo"},
        {w: "Encendedor", h: "Chispa"},
        {w: "Sábana", h: "Cama"},
        {w: "Cuchillo", h: "Filo"},
        {w: "Mochila", h: "Espalda"},
        {w: "Regla", h: "Medida"},
        {w: "Papel", h: "Blanco"},
        {w: "Clavo", h: "Punta"},
        {w: "Moneda", h: "Metal"},
        {w: "Brocha", h: "Pared"},
        {w: "Cuerda", h: "Nudo"},
        {w: "Pila", h: "Energía"},
        {w: "Basurero", h: "Desecho"},
        {w: "Taza", h: "Asa"}
    ],
    celebridades: [
        {w: "Lionel Messi", h: "Balón"},
        {w: "Eduardo Maldonado", h: "HCH"},
        {w: "Salvador Nasralla", h: "X-0"},
        {w: "Renato Álvarez", h: "Frente"},
        {w: "Ariela Cáceres", h: "Control"},
        {w: "Polache", h: "Trova"},
        {w: "Pilo Tejeda", h: "Sopa"},
        {w: "Elsa Oseguera", h: "Redes"},
        {w: "Milagro Flores", h: "Baile"},
        {w: "Cesia Sáenz", h: "Leona"},
        {w: "Juan Carlos Pineda", h: "Fútbol"},
        {w: "Cristina Rodríguez", h: "Noticiero"},
        {w: "Pampichi", h: "Humor"},
        {w: "Nono y Yhee", h: "Los Bohemios"},
        {w: "Kazzabe", h: "Punta"},
        {w: "Guillermo Anderson", h: "Costa"},
        {w: "Heraldo Quiroz", h: "Patrulla"},
        {w: "Donna Rivera", h: "Música"},
        {w: "Mr. JC", h: "Diez"},
        {w: "Syndicate", h: "Urbano"},
        {w: "Menor Menor", h: "Garífuna"},
        {w: "Keyla Martínez", h: "Cocina"},
        {w: "Esdras Amado López", h: "Cholusat"},
        {w: "Coto", h: "Sábado"},
        {w: "Erika Williams", h: "Deportes"},
        {w: "Isabel Zambrano", h: "Cancha"},
        {w: "Kike Espinal", h: "HCH"},
        {w: "Miguel Caballero Leiva", h: "Espectáculos"},
        {w: "David Fortín", h: "Clima"},
        {w: "Allan Paul", h: "HCH"},
        {w: "Carolina Lanza", h: "Noticias"},
        {w: "Jaqueline Redondo", h: "TN5"},
        {w: "Aldo Romero", h: "Periodista"},
        {w: "Jorge Zelaya", h: "Televisión"},
        {w: "Shirley Paz", h: "Chelo"},
        {w: "Duo Los Tres", h: "Guitarras"},
        {w: "Jireh Wilson", h: "Voz"},
        {w: "Lester el Profe", h: "Dembow"},
        {w: "Big Nango", h: "Roatán"},
        {w: "Daba Du", h: "Ritmo"},
        {w: "Oneyda de América", h: "Show"},
        {w: "Tilo Amador", h: "Acordeón"},
        {w: "Moisés Canelo", h: "Festival"},
        {w: "Óscar del Cid", h: "Canto"},
        {w: "Eduardo Andonie", h: "Pop"},
        {w: "Rely Maradiaga", h: "Toque"},
        {w: "Copán Álvarez", h: "Relato"},
        {w: "Carmen Boquín", h: "Internacional"},
        {w: "Dunia Elvir", h: "Emigrar"},
        {w: "Satcha Pretto", h: "Despierta"},
        {w: "Maity Interiano", h: "Univisión"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Michael Jackson", h: "Guante"},
        {w: "Shakira", h: "Cadera"},
        {w: "Albert Einstein", h: "Lengua"},
        {w: "Cristiano Ronaldo", h: "Salto"},
        {w: "Marilyn Monroe", h: "Vestido"},
        {w: "Walt Disney", h: "Ratón"},
        {w: "Elvis Presley", h: "Tupé"},
        {w: "Bill Gates", h: "Ventanas"},
        {w: "Beyoncé", h: "Abeja"},
        {w: "Leonardo da Vinci", h: "Cuadro"},
        {w: "Christopher Colombus", h: "Barcos"},
        {w: "Julio César", h: "Corona"},
        {w: "Steve Jobs", h: "Manzana"},
        {w: "Madonna", h: "Ambición"},
        {w: "Usain Bolt", h: "Rayo"},
        {w: "Tiger Woods", h: "Hoyo"},
        {w: "Pelé", h: "Brasil"},
        {w: "Will Smith", h: "Príncipe"},
        {w: "Angelina Jolie", h: "Labios"},
        {w: "Brad Pitt", h: "Rubio"},
        {w: "Lady Gaga", h: "Monstruo"},
        {w: "Justin Bieber", h: "Flequillo"},
        {w: "Arnold Schwarzenegger", h: "Músculo"},
        {w: "Jackie Chan", h: "Patada"},
        {w: "Bruce Lee", h: "Grito"},
        {w: "Nelson Mandela", h: "Celda"},
        {w: "Abraham Lincoln", h: "Sombrero"},
        {w: "Pablo Picasso", h: "Pincel"},
        {w: "Isaac Newton", h: "Gravedad"},
        {w: "Ludwig van Beethoven", h: "Sordo"},
        {w: "Wolfgang Amadeus Mozart", h: "Piano"},
        {w: "Freddie Mercury", h: "Bigote"},
        {w: "John Lennon", h: "Gafas"},
        {w: "Bob Marley", h: "Rastas"},
        {w: "Charles Chaplin", h: "Bastón"},
        {w: "Tom Cruise", h: "Misión"},
        {w: "Johnny Depp", h: "Pirata"},
        {w: "Britney Spears", h: "Colegio"},
        {w: "Rihanna", h: "Paraguas"},
        {w: "Michael Jordan", h: "Aro"},
        {w: "Elon Musk", h: "Marte"},
        {w: "Stephen Hawking", h: "Silla"},
        {w: "Salvador Dalí", h: "Reloj"},
        {w: "Cleopatra", h: "Egipto"},
        {w: "Juana de Arco", h: "Armadura"},
        {w: "Napoleón Bonaparte", h: "Mano"},
        {w: "Marco Polo", h: "Viaje"},
        {w: "Ghandi", h: "Paz"},
        {w: "Amelia Earhart", h: "Avión"}
    ],
    cine: [
        {w: "Titanic", h: "Barco"},
        {w: "Intensa-Mente", h: "Pensamiento"},
        {w: "Mi Villano Favorito", h: "Minion"},
        {w: "John Wick", h: "Perrito"},
        {w: "Saw", h: "Triciclo"},
        {w: "El Exorcista", h: "Giro"},
        {w: "Pulp Fiction", h: "Maletín"},
        {w: "Inception", h: "Trompo"},
        {w: "Breaking Bad", h: "Cristal"},
        {w: "Better Call Saul", h: "Desierto"},
        {w: "El Lobo de Wall Street", h: "Yate"},
        {w: "Forest Gump", h: "Banca"},
        {w: "Top Gun", h: "Casco"},
        {w: "La La Land", h: "Atardecer"},
        {w: "The Walking Dead", h: "Bate"},
        {w: "The Umbrella Academy", h: "Paraguas"},
        {w: "Cobra Kai", h: "Patada"},
        {w: "Moana", h: "Océano"},
        {w: "Encanto", h: "Vela"},
        {w: "Kung Fu Panda", h: "Fideos"},
        {w: "Shrek 2", h: "Poción"},
        {w: "E.T.", h: "Dedo"},
        {w: "Back to the Future", h: "Relámpago"},
        {w: "El Grinch", h: "Regalo"},
        {w: "The Mandalorian", h: "Casco"},
        {w: "One Piece", h: "Sombrero"},
        {w: "Naruto", h: "Banda"},
        {w: "Dragon Ball Z", h: "Esferas"},
        {w: "Dune", h: "Arena"},
        {w: "Oppenheimer", h: "Hongo"},
        {w: "Interstellar", h: "Reloj"},
        {w: "Deadpool", h: "Chimichanga"},
        {w: "Iron Man", h: "Reactor"},
        {w: "Thor", h: "Martillo"},
        {w: "Wonder Woman", h: "Lazo"},
        {w: "Super Mario Bros", h: "Tubo"},
        {w: "Sonic", h: "Anillo"},
        {w: "A Quiet Place", h: "Silencio"},
        {w: "Bird Box", h: "Venda"},
        {w: "The Crown", h: "Palacio"},
        {w: "Peaky Blinders", h: "Gorra"},
        {w: "Dark", h: "Lluvia"},
        {w: "The Boys", h: "Leche"},
        {w: "The Last of Us", h: "Hongo"},
        {w: "Inside Out 2", h: "Ansiedad"},
        {w: "Garfield", h: "Lasaña"},
        {w: "Sing", h: "Teatro"},
        {w: "Minions", h: "Banana"},
        {w: "Puss in Boots", h: "Leche"},
        {w: "The Flash", h: "Rayo"},
        {w: "Aquaman", h: "Tridente"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "El Rey León", h: "Sabana"},
        {w: "Avatar", h: "Azul"},
        {w: "Harry Potter", h: "Cicatriz"},
        {w: "Star Wars", h: "Sable"},
        {w: "Batman", h: "Murciélago"},
        {w: "Spider-Man", h: "Telaraña"},
        {w: "Toy Story", h: "Juguetes"},
        {w: "Shrek", h: "Pantano"},
        {w: "Juego de Tronos", h: "Dragón"},
        {w: "La Casa de Papel", h: "Máscara"},
        {w: "Stranger Things", h: "Bicicleta"},
        {w: "Los Simpson", h: "Amarillo"},
        {w: "Jurassic Park", h: "Dinosaurio"},
        {w: "Jaws", h: "Aleta"},
        {w: "El Padrino", h: "Gato"},
        {w: "Matrix", h: "Pastilla"},
        {w: "Indiana Jones", h: "Látigo"},
        {w: "Coco", h: "Guitarra"},
        {w: "Frozen", h: "Hielo"},
        {w: "Buscando a Nemo", h: "Aleta"},
        {w: "Misión Imposible", h: "Mecha"},
        {w: "El Joker", h: "Risa"},
        {w: "Los Increíbles", h: "Antifaz"},
        {w: "Ratatouille", h: "Chef"},
        {w: "Up", h: "Globos"},
        {w: "La Bella y la Bestia", h: "Rosa"},
        {w: "Cenicienta", h: "Zapato"},
        {w: "El Chavo del 8", h: "Barril"},
        {w: "Squid Game", h: "Número"},
        {w: "Los Vengadores", h: "Guantelete"},
        {w: "Mi Pobre Angelito", h: "Trampa"},
        {w: "Grease", h: "Brillantina"},
        {w: "El Resplandor", h: "Hacha"},
        {w: "It", h: "Globo"},
        {w: "Rocky", h: "Boxeo"},
        {w: "Rambo", h: "Cinta"},
        {w: "Terminator", h: "Metal"},
        {w: "El Señor de los Anillos", h: "Volcán"},
        {w: "Piratas del Caribe", h: "Brújula"},
        {w: "Cars", h: "Rayo"},
        {w: "Madagascar", h: "Zoológico"},
        {w: "La Purga", h: "Sirena"},
        {w: "Black Panther", h: "Garra"},
        {w: "Braveheart", h: "Cara"},
        {w: "Gladiador", h: "Arena"},
        {w: "King Kong", h: "Edificio"},
        {w: "Godzilla", h: "Radioactivo"},
        {w: "Barbie", h: "Rosado"},
        {w: "Wednesday", h: "Baile"}
    ],
    marcas: [
        {w: "Nike", h: "Gancho"},
        {w: "Tigo", h: "Celular"},
        {w: "Claro", h: "Círculo"},
        {w: "Bancatlán", h: "Honduras"},
        {w: "Ficohsa", h: "Banco"},
        {w: "Diana", h: "Boquitas"},
        {w: "Zambos", h: "Tajaditas"},
        {w: "Leyde", h: "Leche"},
        {w: "Sula", h: "Jugo"},
        {w: "Salva Vida", h: "Cerveza"},
        {w: "Barena", h: "Dorada"},
        {w: "Hyundai", h: "H"},
        {w: "Nissan", h: "Japón"},
        {w: "Kia", h: "Corea"},
        {w: "Jeep", h: "Montaña"},
        {w: "Harley-Davidson", h: "Moto"},
        {w: "Yamaha", h: "Diapasones"},
        {w: "Shell", h: "Concha"},
        {w: "Texaco", h: "Estrella"},
        {w: "Pampers", h: "Bebé"},
        {w: "Huggies", h: "Pañal"},
        {w: "Barbie", h: "Muñeca"},
        {w: "Hot Wheels", h: "Carritos"},
        {w: "PlayStation", h: "Control"},
        {w: "Xbox", h: "X"},
        {w: "Intel", h: "Chip"},
        {w: "HP", h: "Computadora"},
        {w: "Dell", h: "Letra"},
        {w: "Canon", h: "Lente"},
        {w: "Nikon", h: "Foto"},
        {w: "Xiaomi", h: "China"},
        {w: "Huawei", h: "Flor"},
        {w: "Uber", h: "Viaje"},
        {w: "Airbnb", h: "Casa"},
        {w: "FedEx", h: "Caja"},
        {w: "DHL", h: "Amarillo"},
        {w: "Heineken", h: "Verde"},
        {w: "Corona", h: "México"},
        {w: "Nivea", h: "Crema"},
        {w: "Pantene", h: "Pelo"},
        {w: "Head & Shoulders", h: "Caspa"},
        {w: "Victoria's Secret", h: "Ángel"},
        {w: "Gucci", h: "G"},
        {w: "Prada", h: "Triángulo"},
        {w: "Hermès", h: "Carruaje"},
        {w: "Cartier", h: "Joyas"},
        {w: "Lacoste", h: "Cocodrilo"},
        {w: "Under Armour", h: "U"},
        {w: "Reebok", h: "Delta"},
        {w: "Converse", h: "Estrella"},
        {w: "Vans", h: "Patineta"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Coca-Cola", h: "Rojo"},
        {w: "Apple", h: "Mordisco"},
        {w: "McDonald's", h: "Arcos"},
        {w: "Google", h: "Colores"},
        {w: "Amazon", h: "Flecha"},
        {w: "Netflix", h: "N"},
        {w: "Facebook", h: "Azul"},
        {w: "Instagram", h: "Cámara"},
        {w: "WhatsApp", h: "Verde"},
        {w: "YouTube", h: "Botón"},
        {w: "Adidas", h: "Rayas"},
        {w: "Starbucks", h: "Sirena"},
        {w: "Disney", h: "Castillo"},
        {w: "Ferrari", h: "Caballo"},
        {w: "Pepsi", h: "Círculo"},
        {w: "Samsung", h: "Corea"},
        {w: "Toyota", h: "Óvalos"},
        {w: "Mercedes-Benz", h: "Estrella"},
        {w: "Microsoft", h: "Ventana"},
        {w: "Sony", h: "Japón"},
        {w: "Nintendo", h: "Consola"},
        {w: "Puma", h: "Felino"},
        {w: "Lego", h: "Bloque"},
        {w: "IKEA", h: "Mueble"},
        {w: "Rolex", h: "Corona"},
        {w: "Louis Vuitton", h: "Bolso"},
        {w: "Chanel", h: "Perfume"},
        {w: "Zara", h: "Moda"},
        {w: "H&M", h: "Ropa"},
        {w: "Burger King", h: "Corona"},
        {w: "KFC", h: "Coronel"},
        {w: "Subway", h: "Metro"},
        {w: "Pizza Hut", h: "Techo"},
        {w: "Ford", h: "Carro"},
        {w: "Audi", h: "Aros"},
        {w: "Tesla", h: "Rayo"},
        {w: "Twitter", h: "Pájaro"},
        {w: "TikTok", h: "Nota"},
        {w: "Spotify", h: "Ondas"},
        {w: "PayPal", h: "Pago"},
        {w: "Visa", h: "Tarjeta"},
        {w: "Mastercard", h: "Círculos"},
        {w: "Dove", h: "Paloma"},
        {w: "Colgate", h: "Dientes"},
        {w: "Red Bull", h: "Toro"},
        {w: "Monster", h: "Garra"},
        {w: "Gillette", h: "Navaja"},
        {w: "Nestlé", h: "Nido"},
        {w: "Nutella", h: "Avellana"}
    ],
    geografia: [
        {w: "Francia", h: "Torre"},
        {w: "Copán Ruinas", h: "Mayas"},
        {w: "Roatán", h: "Arrecife"},
        {w: "Utila", h: "Buceo"},
        {w: "Cayos Cochinos", h: "Garífuna"},
        {w: "Lago de Yojoa", h: "Pescado"},
        {w: "Pulhapanzak", h: "Cascada"},
        {w: "Pico Bonito", h: "Ceiba"},
        {w: "Fortaleza de San Fernando", h: "Omoa"},
        {w: "Valle de Ángeles", h: "Artesanía"},
        {w: "Santa Rosa de Copán", h: "Café"},
        {w: "La Esperanza", h: "Lenca"},
        {w: "Tela", h: "Acuario"},
        {w: "Trujillo", h: "Cristóbal"},
        {w: "Cedeño", h: "Arena Negra"},
        {w: "Amapala", h: "Volcán"},
        {w: "Comayagua", h: "Campana"},
        {w: "Gracias", h: "Lempira"},
        {w: "Catacamas", h: "Cuevas Talgua"},
        {w: "Choluteca", h: "Puente"},
        {w: "San Pedro Sula", h: "Zorzal"},
        {w: "Tegucigalpa", h: "Cerro Grande"},
        {w: "La Tigra", h: "Pinos"},
        {w: "Panacam", h: "Aves"},
        {w: "Guanaja", h: "Pinos"},
        {w: "Punta Sal", h: "Jeannette"},
        {w: "Lancetilla", h: "Jardín"},
        {w: "El Picacho", h: "Cristo"},
        {w: "Ojojona", h: "Barro"},
        {w: "Siguatepeque", h: "Flores"},
        {w: "Yuscarán", h: "Aguardiente"},
        {w: "Antártida", h: "Pingüino"},
        {w: "Isla de Pascua", h: "Cabezas"},
        {w: "Machu Picchu", h: "Inca"},
        {w: "Petra", h: "Piedra"},
        {w: "Taj Mahal", h: "Mármol"},
        {w: "Monte Everest", h: "Cima"},
        {w: "Cataratas del Niágara", h: "Agua"},
        {w: "Gran Cañón", h: "Río"},
        {w: "Islandia", h: "Aurora"},
        {w: "Hawái", h: "Surf"},
        {w: "Las Vegas", h: "Casino"},
        {w: "Hollywood", h: "Cine"},
        {w: "Mónaco", h: "Carreras"},
        {w: "Sáhara", h: "Dunas"},
        {w: "Amazonas", h: "Selva"},
        {w: "Canadá", h: "Arce"},
        {w: "Bali", h: "Playa"},
        {w: "Singapur", h: "Futuro"},
        {w: "África", h: "Safari"},
        {w: "Noruega", h: "Fiordos"}, // <-- AQUÍ FALTABA UNA COMA
        {w: "Egipto", h: "Pirámide"},
        {w: "Italia", h: "Bota"},
        {w: "China", h: "Muralla"},
        {w: "Brasil", h: "Estatua"},
        {w: "Estados Unidos", h: "Libertad"},
        {w: "Japón", h: "Sol"},
        {w: "México", h: "Sombrero"},
        {w: "Rusia", h: "Frío"},
        {w: "India", h: "Templo"},
        {w: "España", h: "Toro"},
        {w: "Reino Unido", h: "Reloj"},
        {w: "Australia", h: "Canguro"},
        {w: "Canadá", h: "Hoja"},
        {w: "Argentina", h: "Obelisco"},
        {w: "Colombia", h: "Café"},
        {w: "París", h: "Luz"},
        {w: "Nueva York", h: "Manzana"},
        {w: "Roma", h: "Coliseo"},
        {w: "Londres", h: "Niebla"},
        {w: "Grecia", h: "Columnas"},
        {w: "Egipto", h: "Desierto"},
        {w: "Suiza", h: "Alpes"},
        {w: "Holanda", h: "Molino"},
        {w: "Perú", h: "Ruinas"},
        {w: "Chile", h: "Cordillera"},
        {w: "Venecia", h: "Canal"},
        {w: "Dubái", h: "Lujo"},
        {w: "Turquía", h: "Mezquita"},
        {w: "Alemania", h: "Muro"},
        {w: "Pekín", h: "Dragón"},
        {w: "Jerusalén", h: "Muro"},
        {w: "El Vaticano", h: "Papa"},
        {w: "Río de Janeiro", h: "Carnaval"},
        {w: "Moscú", h: "Plaza"},
        {w: "Tokio", h: "Neon"},
        {w: "Ámsterdam", h: "Bici"},
        {w: "Atenas", h: "Sabios"},
        {w: "Barcelona", h: "Sagrada"},
        {w: "Pisa", h: "Inclinada"},
        {w: "Ecuador", h: "Mitad"},
        {w: "Panamá", h: "Canal"},
        {w: "Costa Rica", h: "Pura"},
        {w: "Cuba", h: "Puro"},
        {w: "Venezuela", h: "Salto"},
        {w: "Bolivia", h: "Salar"},
        {w: "Tailandia", h: "Elefante"},
        {w: "Marruecos", h: "Arena"},
        {w: "Portugal", h: "Gallo"},
        {w: "Corea del Sur", h: "Tecnología"}
    ]
};

// --- EL RESTO DEL CÓDIGO ---

let players = [], selectedCategory = '', secretWord = '', currentHint = '', impostors = [], currentPlayerIndex = 0, isWordRevealed = false, timerInterval = null;
let cfgImpostors = 1, cfgMinutes = 3;

function addPlayer() {
    const input = document.getElementById('playerNameInput');
    if (input.value.trim()) {
        players.push(input.value.trim());
        input.value = "";
        renderPlayers();
    }
}

function renderPlayers() {
    document.getElementById('namesList').innerHTML = players.map((p, i) => `
        <div class="stack-item"><span>${p}</span><button onclick="removePlayer(${i})" style="color:var(--danger); background:none; border:none; font-weight:800;">X</button></div>
    `).join('');
    document.getElementById('toStep2').classList.toggle('hidden', players.length < 3);
    document.getElementById('clearListBtn').classList.toggle('hidden', players.length === 0);
}

function removePlayer(i) { players.splice(i, 1); renderPlayers(); }
function clearAllPlayers() { players = []; renderPlayers(); }

function showStep(stepId) {
    document.querySelectorAll('.step').forEach(s => s.classList.add('hidden'));
    document.getElementById(stepId).classList.remove('hidden');
    document.getElementById('backAction').classList.toggle('hidden', stepId === 'step1');
}

function goToStep2() { showStep('step2'); }
function goToStart() { if (timerInterval) clearInterval(timerInterval); showStep('step1'); }

function goBack() {
    if (!document.getElementById('step2').classList.contains('hidden')) showStep('step1');
    else if (!document.getElementById('stepSettings').classList.contains('hidden')) showStep('step2');
    else if (!document.getElementById('game').classList.contains('hidden')) showStep('stepSettings');
}

function selectCategory(cat) {
    selectedCategory = cat;
    cfgImpostors = 1; 
    document.getElementById('impVal').innerText = cfgImpostors;
    showStep('stepSettings');
}

function changeImpostors(val) {
    const maxImp = Math.max(1, Math.floor(players.length / 2)); 
    cfgImpostors = Math.max(1, Math.min(maxImp, cfgImpostors + val));
    document.getElementById('impVal').innerText = cfgImpostors;
}

function changeTime(val) {
    cfgMinutes = Math.max(1, Math.min(10, cfgMinutes + val));
    document.getElementById('timeVal').innerText = cfgMinutes;
}

function startGame() {
    let pool = [];
    if (selectedCategory === 'todas') {
        pool = Object.values(database).flat();
    } else {
        pool = database[selectedCategory];
    }
    
    if (!pool || pool.length === 0) return alert("Categoría vacía");
    
    const item = pool[Math.floor(Math.random() * pool.length)];
    secretWord = item.w;
    currentHint = item.h;

    impostors = [];
    let poolIndices = [...Array(players.length).keys()];
    for(let i=0; i<cfgImpostors; i++) {
        let randIdx = Math.floor(Math.random() * poolIndices.length);
        impostors.push(poolIndices.splice(randIdx, 1)[0]);
    }

    currentPlayerIndex = 0;
    showStep('game');
    updateTurnUI();
}

function updateTurnUI() {
    document.getElementById('turnTitle').innerText = players[currentPlayerIndex];
    document.getElementById('wordBox').classList.add('hidden');
    document.getElementById('mainBtn').innerText = "VER PALABRA";
    isWordRevealed = false;
}

function flow() {
    if (!isWordRevealed) {
        const isImp = impostors.includes(currentPlayerIndex);
        document.getElementById('secretWord').innerText = isImp ? "¡ERES EL IMPOSTOR!" : secretWord;
        document.getElementById('secretWord').style.color = isImp ? "var(--danger)" : "var(--accent)";
        
        // Se añade la condición: debe ser impostor Y las pistas deben estar activadas
        const mostrarPista = isImp && document.getElementById('hintToggle').checked;
        document.getElementById('hintArea').classList.toggle('hidden', !mostrarPista);
        
        document.getElementById('hintText').innerText = currentHint;
        document.getElementById('wordBox').classList.remove('hidden');
        document.getElementById('mainBtn').innerText = "ENTENDIDO";
        isWordRevealed = true;
    } else {
        currentPlayerIndex++;
        if (currentPlayerIndex < players.length) updateTurnUI();
        else startDebate();
    }
}

function startDebate() {
    showStep('finish');
    const starter = players[Math.floor(Math.random() * players.length)];
    document.getElementById('whoStarts').innerHTML = `🎙️ INICIA LA RONDA: <br><span style="color:var(--accent); font-size:1.5rem;">${starter}</span>`;
    document.getElementById('impostorResult').classList.add('hidden');
    document.getElementById('endOptions').classList.add('hidden');
    document.getElementById('revealBtn').classList.remove('hidden');
    document.getElementById('timerDisplay').innerText = `${cfgMinutes}:00`;
    startTimer(cfgMinutes * 60);
}

function startTimer(seconds) {
    if (timerInterval) clearInterval(timerInterval);
    let t = seconds;
    timerInterval = setInterval(() => {
        let m = Math.floor(t / 60), s = t % 60;
        document.getElementById('timerDisplay').innerText = `${m}:${s < 10 ? '0' : ''}${s}`;
        if (--t < 0) clearInterval(timerInterval);
    }, 1000);
}

function revealImpostor() {
    const names = impostors.map(idx => players[idx]).join(", ");
    document.getElementById('impostorName').innerText = names;
    document.getElementById('impostorResult').classList.remove('hidden');
    document.getElementById('endOptions').classList.remove('hidden');
    document.getElementById('revealBtn').classList.add('hidden');
    document.getElementById('whoStarts').innerHTML = "";
    if (timerInterval) clearInterval(timerInterval);
}

function newRound() { showStep('step2'); }
